### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by MehmetFiratKomurcu** [Trendyol/kafka-retry-job#15]
Currently, our integration tests are failing, yet our CI/CD pipeline still allows deployment of new versions despite these failures. This needs to be addressed to prevent potential issues in production.

The test failures began after adding SASL configurations to the producer and consumers. Interestingly, when these configurations are commented out, the tests pass successfully. We need to investigate the root cause of these test failures in the context of the SASL configurations and implement a fix.

**Comment by ahmetfurkankavraz** [comment]
this feature is completed with https://github.com/Trendyol/kafka-retry-job/pull/38
